# Generated by Django 4.2.4 on 2023-10-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneAuth",
            fields=[
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="휴대폰 번호",
                    ),
                ),
                ("auth_number", models.CharField(max_length=6, verbose_name="인증 번호")),
            ],
            options={
                "db_table": "auth",
            },
        ),
    ]
