# Generated by Django 4.2.4 on 2023-10-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_phone_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneauth",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
