# Generated by Django 4.2.4 on 2023-10-27 08:49

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("user_phone_auth", "0002_phoneauth_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneauth",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="phoneauth",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
