# Generated by Django 4.2.4 on 2023-10-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_phone_auth", "0003_phoneauth_created_alter_phoneauth_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneauth",
            name="auth_number",
            field=models.IntegerField(verbose_name="인증 번호"),
        ),
    ]
