# Generated by Django 4.2.5 on 2023-09-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomyNews',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('posting_date', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('order', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ItScienceNews',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('posting_date', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('order', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='LifeCultureNews',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('posting_date', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('order', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticsNews',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('posting_date', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('order', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyNews',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('posting_date', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('order', models.CharField(max_length=12)),
            ],
        ),
    ]
