# Generated by Django 4.2.4 on 2023-09-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "title",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("posting_date", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("order", models.IntegerField()),
            ],
        ),
    ]
