# Generated by Django 4.2.4 on 2023-09-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="EconomyNews",
            fields=[
                (
                    "title",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("posting_date", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("order", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="ItScienceNews",
            fields=[
                (
                    "title",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("posting_date", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("order", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="LifeCultureNews",
            fields=[
                (
                    "title",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("posting_date", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("order", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="SocietyNews",
            fields=[
                (
                    "title",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("posting_date", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("order", models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameModel(
            old_name="News",
            new_name="PoliticsNews",
        ),
    ]
